### ISSUE TITLE
Detect .well/knowns that do not have a version number 

### ISSUE THREAD

**Issue by SebastianZimmeck** [privacy-tech-lab/optmeowt-browser-extension#139] opened 2021-02-11 17:37 UTC
The New York Times has a [.well-known](https://www.nytimes.com/.well-known/gpc.json), however, without the version number. Currently, OptMeowt does not detect the .well-known. So, I think we should change the detection on our end. It works if am on https://www.nytimes.com/.well-known/gpc.json but not if I am just on https://www.nytimes.com/.

**Comment by SebastianZimmeck** [comment] 2021-02-15 20:26
Maybe, this is a timing issue. The formatting seems to be OK.

**Comment by kalicki1** [comment] 2021-03-09 01:25
As discussed in our meeting earlier today, I found that this issue was not caused by OptMeowt being unable to find the GPC.json file, but rather a reset happening when sub-frames are loaded on the NYT site. 

This involves the Chrome APIs, since I have a local variable reset to `false` when a page is detected to refresh. I did not know that a listener connected to the Chrome `onBeforeNavigate` API was triggered even when sub-frames were loaded. Checking to see if a parent frame is being loaded resolved this issue. 

Since I have pushed the resulting bug fixes, I will go ahead and close this issue.

**Closed** 2021-03-09 01:25 UTC
Labels: bug
